### ISSUE TITLE
Make easier to know the necessary dependencies

### ISSUE THREAD

**Issue by ivanhercaz** [kaepora/resilience#2] opened 2019-06-01 16:37 UTC
Hi @kaepora,
First of all, thank you very much for this tool. I am trying to test it because if it works fine I would like to share it with all the people who ask me about an easy way to block ads globally and not a one-browser solution. This is even useful for Windows users, due I read many people asking about a similar app for Windows but easier to configure and install).

However, I would like to propose you to make easier to know the dependencies. When I execute `make dependencies` I get that one of the next dependencies isn't installed: `gdk-3.0 glib-2.0 gobject-2.0`.

Could you make it easier? Would it happen in Windows something similar?

Regards,
Iván

**Comment by kaepora** [comment] 2019-06-01 16:58
@ivanhercaz I haven't tested this under Linux at all yet, but no such dependency should be required in Windows or macOS.

**Comment by kaepora** [comment] 2019-06-01 17:00
Duplicate of #4 apparently, which has been answered just now.

**Closed by kaepora** 2019-06-01 17:00 UTC
Labels: question

**Comment by ivanhercaz** [comment] 2019-06-01 17:56
> Duplicate of #4 apparently, which has been answered just now.

It might be, but my intention with this one was to justify the reasons by I think it is necessary to have a clear dependency instructions. Of course, it is related with the one opened yet, but also of any dependency related question.

**Comment by kaepora** [comment] 2019-06-02 10:01
@ivanhercaz Make a pull request to the README.

**Comment by ivanhercaz** [comment] 2019-06-02 10:05
All right @kaepora! I will do it later :+1:
